"""add hospital regist

Revision ID: f4561d1a8970
Revises: 7613d3e82505
Create Date: 2020-11-29 10:41:47.506396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4561d1a8970'
down_revision = '7613d3e82505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_regists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regist_flg', sa.Boolean(), nullable=True),
    sa.Column('from_hospital_id', sa.Integer(), nullable=False),
    sa.Column('to_hospital_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['to_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_regists')
    # ### end Alembic commands ###
